# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /SAILCOIN_BOT

# Copy the current directory contents into the container at /SAILCOIN_BOT
COPY . /SAILCOIN_BOT

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /SAILCOIN_BOT/requirements.txt

# Make sure your application listens on port 8443
# Replace "app.py" with the actual filename of your Python script
CMD ["python", "app.py"]

# Expose port 8443 to allow incoming connections
EXPOSE 8443